routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function() {
    //Logged-in user with the extended group
    Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('Admin')->group(function () {
        Route::prefix('users')->name('users.')->group(function () {
            Route::get('/index', 'UserController@index')->name('index');
            //add
            Route::get('create', 'UserController@create')->name('create');//list function add edit remove
            Route::post('/store', 'UserController@store')->name('store');//list function add edit remove
            //edit
            Route::get('/show/{id}', 'UserController@show')->name('show');//update page
            Route::post('/update/{id}', 'UserController@update')->name('update');//update
            //remove
            Route::get('/destroy/{id}', 'UserController@destroy')->name('destroy');//remove
            //ban
            Route::get('/ban/{id}', 'UserController@ban')->name('ban');//banned
            //unban
            Route::get('/unban/{id}', 'UserController@unban')->name('unban');//unbanned
        });
        Route::prefix('catalog')->name('catalog.')->group(function () {
            Route::get('/index', 'PizzaController@index')->name('index');

            Route::get('create', 'PizzaController@create')->name('create');//list function add edit remove
            Route::post('/store', 'PizzaController@store')->name('store');//list function add edit remove
            //edit
            Route::get('/show/{id}', 'PizzaController@show')->name('show');//update page
            Route::post('/update/{id}', 'PizzaController@update')->name('update');//update
            //remove
            Route::get('/delete/{id}', 'PizzaController@delete')->name('delete');//remove
            //ban
            Route::get('/ban/{id}', 'PizzaController@ban')->name('ban');//banned
            //unban
            Route::get('/unban/{id}', 'PizzaController@unban')->name('unban');//unbanned
            Route::prefix('dop')->name('dop.')->group(function () {
                Route::get('/index', 'DopController@index')->name('index');

                Route::get('create', 'DopController@create')->name('create');//list function add edit remove
                Route::post('/store', 'DopController@store')->name('store');//list function add edit remove
                //edit
                Route::get('/show/{id}', 'DopController@show')->name('show');//update page
                Route::post('/update/{id}', 'DopController@update')->name('update');//update
                //remove
                Route::get('/delete/{id}', 'DopController@delete')->name('delete');//remove
                //ban
                Route::get('/ban/{id}', 'DopController@ban')->name('ban');//banned
                //unban
                Route::get('/unban/{id}', 'DopController@unban')->name('unban');//unbanned
            });
        });
        Route::prefix('order')->name('order.')->group(function () {
            Route::get('/index', 'OrderController@index')->name('index');
            Route::get('/edit/{id}', 'OrderController@show')->name('edit');
            Route::post('/update/{id} ', 'OrderController@update')->name('update');
        });
    });

    Route::namespace('Client')->prefix('client')->name('client.')->middleware('Client')->group(function () {
        Route::prefix('order')->name('order.')->group(function () {
        });
    });
});
Route::namespace('Client')->prefix('client')->name('client.')->group(function ()  {
    Route::get('/index', 'CatalogController@index')->name('index');
    Route::get('/check', 'CatalogController@check')->name('check');
    Route::get('/pizza', 'CatalogController@pizza')->name('pizza');
    Route::get('/drink', 'CatalogController@drink')->name('drink');
    Route::get('/fetch_data', 'CatalogController@fetch_data')->name('fetch_data');
    Route::get('/search', 'CatalogController@search')->name('search');
    Route::get('/map', 'CatalogController@map')->name('map');
    Route::prefix('order')->name('order.')->group(function () {
        Route::post('/guest', 'OrderController@guest')->name('guest');
        Route::get('/payment', 'OrderController@payment')->name('payment');
        Route::post('/post', 'OrderController@post')->name('post');
        Route::get('/index', 'OrderController@index')->name('index');
        Route::post('/user', 'OrderController@user')->name('user');
        Route::get('/store', 'OrderController@store')->name('store');
        Route::post('/create', 'OrderController@create')->name('create');
        Route::get('/delete/{id}', 'OrderController@delete')->name('delete');
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role','phone','address',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    protected $dates = ['deleted_at'];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserAdminRequest;
use App\Http\Requests\UserEditRequest;
use App\Mail\MailNotification;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;
use Illuminate\Support\Facades\Mail;
use App\User;


class UserController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function start()
    {
        return view('admin.admin');
    }
    public function index()
    {
        $admins = User::where('role', 0)
            ->paginate(2, ["*"], "admin");
        $managers = User::where('role', 1)
            ->paginate(2, ["*"], "manager");
        $users = User::where('role', 2)
            ->paginate(2, ["*"], "user");
        $bans = User::onlyTrashed()
            ->paginate(2, ["*"], "ban");

        return view('admin.users.index', compact('admins','managers','users','bans'));
    }
    public function create()
    {
        return view('admin.users.create');
    }
    public function show($id)
    {
        $post = User::where('id', $id)->first();
        return view('admin.users.edit', ['users' => $post],['id' => $id]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserAdminRequest $request)
    {
        $random = str_shuffle('abcdefghjklmnopqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ234567890!$%^&!$%^&');
        $password = substr($random, 0, 10);
        $user=collect();
        $user->put('password',$password);
        $user->put('email',$request['email']);
        $user->put('name',$request['name']);
        User::insert([
            'name' =>  $request['name'],
            'email' => $request['email'],
            'phone'=> $request['phone'],
            'address'=> $request['address'],
            'created_at'=> Carbon::now()->toDateTimeString(),
            'updated_at'=> Carbon::now()->toDateTimeString(),
            'email_verified_at'=> Carbon::now()->toDateTimeString(),
            'role'=> $request['role'],
            'password' => Hash::make($password),
        ]);
        Mail::to($request['email'])->send(new MailNotification($user));
        return redirect()->route('admin.users.index')->with(['message' => 'Data save']);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */



    public function update(UserEditRequest $request, $id)
    {
        User::where('id', $id)
            ->update([
                'name' =>  $request['name'],
                'email' => $request['email'],
                'phone'=> $request['phone'],
                'address'=> $request['address'],
                'role'=> $request['role'],
                'updated_at'=> Carbon::now()->toDateTimeString(),
                'email_verified_at'=> Carbon::now()->toDateTimeString(),
                'password' => Hash::make($request['password']),
            ]);
        Mail::to($request['email'])->send(new MailNotification($request));
        return redirect()->route('admin.users.index')->with('success','User updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $baned = User::withTrashed()->findOrFail($id);
        $baned->forceDelete();
        return redirect()->route('admin.users.index');
    }
    public function ban($id)
    {
        User::destroy($id);
        return redirect()->route('admin.users.index');
    }
    public function unban($id)
    {
        User::withTrashed()
            ->where('id', $id)
            ->restore();
        return redirect()->route('admin.users.index');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>
                    <div class="card-body">
                        <div class="container">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                        </div>
                        <body>
                        <div class="container">

                            <form method="POST" action="{{ route('admin.users.store') }}">
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <label for="name">Print name</label>
                                    <input class="form-control"  placeholder="name" name="name" required>
                                </div>
                                <div class="form-group">
                                    <label for="email">Print email</label>
                                    <input class="form-control"  placeholder="email" name="email" required>
                                </div>
                                <div class="form-group">
                                    <label for="phone">Print phone</label>
                                    <input class="form-control"  placeholder="phone" name="phone" required>
                                </div>
                                <div class="form-group">
                                    <label for="address">Print address</label>
                                    <input class="form-control"  placeholder="address" name="address" required>
                                </div>
                                <div class="list-group">
                                    <select name='role' class="category_id">
                                        <option   value=0 >Admin</option>
                                        <option   value=1 >Manager</option>
                                        <option   value=2 >Client</option>
                                    </select>
                                </div>

                                <button type="submit" class="btn btn-default">add</button>
                            </form>
                        </div>
                        </body>




                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>
                    <div class="card-body">
                        <div class="container">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                        </div>
                        <body>
                        <div class="container">

                            <form method="post" action="{{ route('admin.users.update',$users->id)}}" >
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <label for="name">Print name</label>
                                    <input class="form-control"  placeholder="{{$users->name}}" name="name" required>
                                </div>
                                <div class="form-group">
                                    <label for="email">Print email</label>
                                    <input class="form-control"  placeholder="{{$users->email}}" name="email" required>
                                </div>
                                <div class="form-group">
                                    <label for="password">Print password</label>
                                    <input class="form-control"  placeholder="password" name="password" required>
                                </div>
                                <div class="form-group">
                                    <label for="phone">Print phone</label>
                                    <input class="form-control"  placeholder="{{$users->phone}}" name="phone" required>
                                </div>
                                <div class="form-group">
                                    <label for="address">Print address</label>
                                    <input class="form-control"  placeholder="{{$users->address}}" name="address" required>
                                </div>
                                <div class="list-group">
                                    <select name='role' class="category_id">
                                        <option   value=0 >Admin</option>
                                        <option   value=1 >Manager</option>
                                        <option   value=2 >Client</option>
                                    </select>
                                </div>

                                <button type="submit" class="btn btn-default">update</button>
                            </form>
                        </div>
                        </body>


                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="container-fluid">
<style>
    table {width: 600px;}
    th {width: 20%;}
    td:first-child {width: 30%;}
</style>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>
                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <body>
                        <div class="container">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif


                        </div>

                        </body>
                        Admin redactor
                        <br>
                        <a class="btn btn-success"  href="{{ route('admin.users.create') }}"  type="submit">
                            {{ __('User create') }}
                        </a>
                        <table class="table table" >
                            <thead>
                            <tr>
                                <th>id</th>
                                <th>name</th>
                                <th>phone</th>
                                <th>email</th>
                                <th>address</th>
                                <th></th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach($admins as $key => $value)
                                <tr>
                                    {{ csrf_field() }}
                                    <td >{{ $value->id }}</td>
                                    <td>{{ $value->name }}</td>
                                    <td>{{ $value->phone }}</td>
                                    <td>{{ $value->email }}</td>
                                    <td>{{$value->address}}</td>
                                    <td>  <a class="btn btn-danger"  href="{{ route('admin.users.destroy',$value->id)}}" type="submit" name="' . $key . '">
                                            {{ csrf_field() }}{{ __('remove') }}  </a>
                                        <a class="btn btn-warning" href="{{ route('admin.users.show',$value->id)}}" type="submit" name="' . $key . '">
                                            {{('edit') }}  </a>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <input type="hidden" id="token" value="{{ csrf_token() }}">
                        {{ $admins->fragment('$admin')->links() }}
                            <div>Managers</div>

                            <br>
                            <table class="table table">
                                <thead>
                                <tr>
                                    <th>id</th>
                                    <th>name</th>
                                    <th>phone</th>
                                    <th>email</th>
                                    <th>address</th>
                                    <th></th>

                                </tr>
                                </thead>
                                <tbody>
                                @foreach($managers as $key => $value)
                                    <tr>
                                        {{ csrf_field() }}
                                        <td >{{ $value->id }}</td>
                                        <td>{{ $value->name }}</td>
                                        <td>{{ $value->phone }}</td>
                                        <td>{{ $value->email }}</td>
                                        <td>{{$value->address}}</td>
                                        <td>  <a class="btn btn-danger"  href="{{ route('admin.users.destroy',$value->id)}}" type="submit" name="' . $key . '">
                                                {{ csrf_field() }}{{ __('remove') }}  </a>
                                            <a class="btn btn-warning" href="{{ route('admin.users.show',$value->id)}}" type="submit" name="' . $key . '">
                                                {{('edit') }}  </a>
                                        </td>

                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <input type="hidden" id="token" value="{{ csrf_token() }}">
                            {{ $managers->fragment('$manager')->links() }}


                            <div>Clients</div>

                            <br>
                        <table class="table table">
                            <thead>
                            <tr>
                                <th>id</th>
                                <th>name</th>
                                <th>phone</th>
                                <th>email</th>
                                <th>address</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $key => $value)
                                <tr>
                                    {{ csrf_field() }}
                                    <td >{{ $value->id }}</td>
                                    <td>{{ $value->name }}</td>
                                    <td>{{ $value->phone }}</td>
                                    <td>{{ $value->email }}</td>
                                    <td>{{$value->address}}</td>
                                    <td>
                                        <a class="btn btn-danger"  href="{{ route('admin.users.destroy',$value->id)}}" type="submit" >
                                            {{ __('remove') }}  </a>
                                        <a class="btn btn-warning" href="{{ route('admin.users.show',$value->id)}}" type="submit">
                                            {{('edit') }}  </a>
                                        <a class="btn btn-primary" href="{{ route('admin.users.ban',$value->id)}}" type="submit" >
                                            {{('ban user') }}  </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <input type="hidden" id="2" value="{{ csrf_token() }}">
                        {{ $users->fragment('user')->links()  }}
                        <table class="table table">
                            <thead>
                            <tr>
                                <th>id</th>
                                <th>name</th>
                                <th>phone</th>
                                <th>email</th>
                                <th>address</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($bans as $key => $value)
                                <tr>
                                    {{ csrf_field() }}
                                    <td >{{ $value->id }}</td>
                                    <td>{{ $value->name }}</td>
                                    <td>{{ $value->phone }}</td>
                                    <td>{{ $value->email }}</td>
                                    <td>{{$value->address}}</td>
                                    <td>
                                        <a class="btn btn-danger"  href="{{ route('admin.users.destroy',$value->id)}}" type="submit" >
                                            {{ __('remove') }}  </a>
                                        <a class="btn btn-warning" href="{{ route('admin.users.show',$value->id)}}" type="submit">
                                            {{('edit') }}  </a>
                                        <a class="btn btn-primary" href="{{ route('admin.users.unban',$value->id)}}" type="submit" >
                                            {{('unban user') }}  </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <input type="hidden" id="2" value="{{ csrf_token() }}">
                        {{ $bans->fragment('ban')->links()  }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection