routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function() {
    //Logged-in user with the extended group
    Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('Admin')->group(function () {
        Route::prefix('users')->name('users.')->group(function () {
            Route::get('/index', 'UserController@index')->name('index');
            //add
            Route::get('create', 'UserController@create')->name('create');//list function add edit remove
            Route::post('/store', 'UserController@store')->name('store');//list function add edit remove
            //edit
            Route::get('/show/{id}', 'UserController@show')->name('show');//update page
            Route::post('/update/{id}', 'UserController@update')->name('update');//update
            //remove
            Route::get('/destroy/{id}', 'UserController@destroy')->name('destroy');//remove
            //ban
            Route::get('/ban/{id}', 'UserController@ban')->name('ban');//banned
            //unban
            Route::get('/unban/{id}', 'UserController@unban')->name('unban');//unbanned
        });
        Route::prefix('catalog')->name('catalog.')->group(function () {
            Route::get('/index', 'PizzaController@index')->name('index');

            Route::get('create', 'PizzaController@create')->name('create');//list function add edit remove
            Route::post('/store', 'PizzaController@store')->name('store');//list function add edit remove
            //edit
            Route::get('/show/{id}', 'PizzaController@show')->name('show');//update page
            Route::post('/update/{id}', 'PizzaController@update')->name('update');//update
            //remove
            Route::get('/delete/{id}', 'PizzaController@delete')->name('delete');//remove
            //ban
            Route::get('/ban/{id}', 'PizzaController@ban')->name('ban');//banned
            //unban
            Route::get('/unban/{id}', 'PizzaController@unban')->name('unban');//unbanned
            Route::prefix('dop')->name('dop.')->group(function () {
                Route::get('/index', 'DopController@index')->name('index');

                Route::get('create', 'DopController@create')->name('create');//list function add edit remove
                Route::post('/store', 'DopController@store')->name('store');//list function add edit remove
                //edit
                Route::get('/show/{id}', 'DopController@show')->name('show');//update page
                Route::post('/update/{id}', 'DopController@update')->name('update');//update
                //remove
                Route::get('/delete/{id}', 'DopController@delete')->name('delete');//remove
                //ban
                Route::get('/ban/{id}', 'DopController@ban')->name('ban');//banned
                //unban
                Route::get('/unban/{id}', 'DopController@unban')->name('unban');//unbanned
            });
        });
        Route::prefix('order')->name('order.')->group(function () {
            Route::get('/index', 'OrderController@index')->name('index');
            Route::get('/edit/{id}', 'OrderController@show')->name('edit');
            Route::post('/update/{id} ', 'OrderController@update')->name('update');
        });
    });

    Route::namespace('Client')->prefix('client')->name('client.')->middleware('Client')->group(function () {
        Route::prefix('order')->name('order.')->group(function () {
        });
    });
});
Route::namespace('Client')->prefix('client')->name('client.')->group(function ()  {
    Route::get('/index', 'CatalogController@index')->name('index');
    Route::get('/check', 'CatalogController@check')->name('check');
    Route::get('/pizza', 'CatalogController@pizza')->name('pizza');
    Route::get('/drink', 'CatalogController@drink')->name('drink');
    Route::get('/fetch_data', 'CatalogController@fetch_data')->name('fetch_data');
    Route::get('/search', 'CatalogController@search')->name('search');
    Route::get('/map', 'CatalogController@map')->name('map');
    Route::prefix('order')->name('order.')->group(function () {
        Route::post('/guest', 'OrderController@guest')->name('guest');
        Route::get('/payment', 'OrderController@payment')->name('payment');
        Route::post('/post', 'OrderController@post')->name('post');
        Route::get('/index', 'OrderController@index')->name('index');
        Route::post('/user', 'OrderController@user')->name('user');
        Route::get('/store', 'OrderController@store')->name('store');
        Route::post('/create', 'OrderController@create')->name('create');
        Route::get('/delete/{id}', 'OrderController@delete')->name('delete');
    });
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Kyslik\ColumnSortable\Sortable;
use Illuminate\Support\Facades\Storage;

class Product extends Model
{
    use Sortable;
    use SoftDeletes;
    protected $table = 'product';
    protected $fillable = [
        'title', 'prise', 'image','parts','sale','hot','rating','vegetarian',
    ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    public $sortable = ['title', 'prise','parts', 'created_at', 'updated_at'];
    protected $dates = ['deleted_at'];
    public static  function addFile($file,$image)
    {
        $imageName = time().'.'.$image->getClientOriginalExtension();
        Storage::putFileAs(
            'image', $file, $imageName
        );
        return $imageName;
    }
    public function getImageUrlAttribute() {
        return Storage::url('image/'.$this->image);
    }
}

app/Http/Controllers/Client/CatalogController.php
<?php

namespace App\Http\Controllers\Client;

use App\Dop;
use App\Http\Controllers\Controller;
use App\Http\Requests\SearchRequest;
use App\Order;
use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;



class CatalogController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pizza = Product::where('pizza',true)->sortable()->get();
        $dop=Dop::get();
        $drink= Product::Where('pizza',false)->sortable()->get();
        return view('client.catalog.index')->with(compact('pizza','drink','dop'));
    }

    public function search(SearchRequest $request)
    {
        $dop=Dop::get();
        $pizza = Product::where('title',$request->search)->get();
        return view('client.catalog.search')->with(compact('pizza','dop'));
    }

    public function pizza()
    {
        $dop=Dop::get();
        $pizza = Product::where('pizza',true)->sortable()->get();
        return view('client.catalog.pizza')->with(compact('pizza','dop'));
    }

    public function drink()
    {
        $drink= Product::Where('pizza',false)->sortable()->get();
        return view('client.catalog.drink')->with(compact('drink'));
    }

    public function check(Request $request)
    {
        $product=Product::where('pizza',true)->get();

        if ($request->data[0] == 1) {
            $product=$product->where('hot',true);
        }
        if ($request->data[1] == 1) {
            $product=$product->where('Vegetarian',true);
        }
        if ($request->data[2] == 1) {
            $product=$product->where('Sale ',true);
        }
        return $product;
    }

    public function show($id)
    {
        $post = Product::find($id);
        return view('client.catalog.edit', compact('post','id'));
    }
    public function map()
    {
        $order=Order::where('user_id',Auth::id())->get();
        return view('client.map')->with(compact('order'));
    }
}

resources/views/admin/catalog/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>
                    <div class="card-body">
                        <div class="container">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                        </div>
                        <body>
                        <div class="container">

                            <form action="{{ route('admin.catalog.store') }}" method="POST" enctype="multipart/form-data">
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <label for="name">Print title</label>
                                    <input class="form-control"  placeholder="title" name="title" required>
                                </div>
                                <div class="form-group">
                                    <label for="name">Print prise</label>
                                    <input class="form-control" type="number" placeholder="prise" name="prise" required>
                                </div>
                                <div class="form-group">
                                    <label for="email">Print text</label>
                                    <input class="form-control"  placeholder="parts" name="parts" required>
                                </div>
                                <div class="col-md-6">
                                    <input required type="file"  class="form-control" name="image">
                                </div>
                                <div class="col-md-10">Hot
                                <input type="checkbox" id="hot" name="hot" value=1>
                                    Pizza
                                    <input type="checkbox" id="pizza" name="pizza" value=1>
                                    Vegetarian
                                    <input type="checkbox" id="vegetarian" name="vegetarian" value=1>
                                    Sale
                                    <input type="checkbox" id="sale" name="sale" value=1>

                                </div>

                                <button type="submit" class="btn btn-default">add</button>
                            </form>
                        </div>
                        </body>



                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/catalog/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>
                    <div class="card-body">
                        <div class="container">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                        </div>
                        <body>
                        <div class="container">
                            <form action="{{ route('admin.catalog.update',$post->id) }}" method="POST" enctype="multipart/form-data">
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <label for="name">Print title</label>
                                    <input class="form-control"  placeholder={{$post->title}} name="title" required>
                                </div>
                                <div class="form-group">
                                    <label for="name">Print prise</label>
                                    <input class="form-control" type="number" placeholder={{$post->prise}} name="prise" required>
                                </div>
                                <div class="form-group">
                                    <label for="email">Print text</label>
                                    <input class="form-control"  placeholder={{$post->parts}} name="parts" required>
                                </div>
                                <div class="col-md-6">
                                    <input required type="file"  class="form-control" name="image">
                                </div>
                                <div class="col-md-10">Hot
                                    <input type="checkbox" id="hot" name="hot" value=1>
                                    Pizza
                                    <input type="checkbox" id="pizza" name="pizza" value=1>
                                    Vegetarian
                                    <input type="checkbox" id="vegetarian" name="vegetarian" value=1>
                                    Sale
                                    <input type="checkbox" id="sale" name="sale" value=1>
                                </div>
                                <button type="submit" class="btn btn-default">add</button>
                            </form>
                        </div>
                        </body>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/catalog/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div>
                <a href="{{route('admin.catalog.dop.index')}}" class="btn btn-danger">Dopping</a>
            </div>
            <div class="col-md-10">
                <div class="">
                    <a href="{{route('admin.catalog.create')}}" class="btn btn-primary">Create pizza</a>
                </div>
                <div class="card">
                    <div class="card-header">Pizza</div>
                    <div class="card">
                        <div class="row">
                            @foreach($pizza as $key => $value)
                                {{ csrf_field() }}
                                <div class="col-sm-4">
                                    <div class="card">
                                        <div class="card-body">
                                            <h5 class="card-title">{{$value->title}}</h5>
                                            <img src="{{ asset($value->image_url)}}">
                                            <p class="card-text">{{$value->parts}}</p>
                                            <span class="price">₽ {{$value->prise}}</span>
                                            <a href="{{route('admin.catalog.delete',$value->id)}}" class="btn btn-primary">Delete</a>
                                            <a href="{{route('admin.catalog.show',$value->id)}}" class="btn btn-primary">Edit</a>
                                            <a href="{{route('admin.catalog.ban',$value->id)}}" class="btn btn-primary">Add archive</a>
                                        </div>
                                    </div>
                                    <br>
                                </div>
                            @endforeach

                        </div>
                    </div>
                </div>
                <br>
                <div class="card">
                    <div class="card-header">Drink</div>
                    <div class="card">
                        <div class="row">
                            @foreach($drink as $key => $value)
                                {{ csrf_field() }}
                            <div class="col-sm-4">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title">{{$value->title}}</h5>
                                        <img src="{{ asset($value->image_url)}}">
                                        <p class="card-text">{{$value->parts}}</p>
                                        <span class="price">₽ {{$value->prise}}</span>
                                        <a href="{{route('admin.catalog.delete',$value->id)}}" class="btn btn-primary">Delete</a>
                                        <a href="{{route('admin.catalog.show',$value->id)}}" class="btn btn-primary">Edit</a>
                                        <a href="{{route('admin.catalog.ban',$value->id)}}" class="btn btn-primary">Add archive</a>
                                    </div>
                                </div>
                                <br>
                            </div>
                         @endforeach

                        </div>
                    </div>
                </div>
                <br>
                <div class="card">
                    <div class="card-header">Deletes</div>
                    <div class="card">
                        <div class="row">
                            @foreach($deletes as $key => $value)
                                {{ csrf_field() }}
                                <div class="col-sm-4">
                                    <div class="card">
                                        <div class="card-body">
                                            <h5 class="card-title">{{$value->title}}</h5>
                                            <img src="{{ asset($value->image_url)}}">
                                            <p class="card-text">{{$value->parts}}</p>
                                            <span class="price">₽ {{$value->prise}}</span>
                                            <a href="{{route('admin.catalog.delete',$value->id)}}" class="btn btn-primary">Delete</a>
                                            <a href="{{route('admin.catalog.show',$value->id)}}" class="btn btn-primary">Edit</a>
                                            <a href="{{route('admin.catalog.unban',$value->id)}}" class="btn btn-primary">Add catalog</a>
                                        </div>
                                    </div>
                                    <br>
                                </div>
                            @endforeach

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection