routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function() {
    //Logged-in user with the extended group
    Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('Admin')->group(function () {
        Route::prefix('users')->name('users.')->group(function () {
            Route::get('/index', 'UserController@index')->name('index');
            //add
            Route::get('create', 'UserController@create')->name('create');//list function add edit remove
            Route::post('/store', 'UserController@store')->name('store');//list function add edit remove
            //edit
            Route::get('/show/{id}', 'UserController@show')->name('show');//update page
            Route::post('/update/{id}', 'UserController@update')->name('update');//update
            //remove
            Route::get('/destroy/{id}', 'UserController@destroy')->name('destroy');//remove
            //ban
            Route::get('/ban/{id}', 'UserController@ban')->name('ban');//banned
            //unban
            Route::get('/unban/{id}', 'UserController@unban')->name('unban');//unbanned
        });
        Route::prefix('catalog')->name('catalog.')->group(function () {
            Route::get('/index', 'PizzaController@index')->name('index');

            Route::get('create', 'PizzaController@create')->name('create');//list function add edit remove
            Route::post('/store', 'PizzaController@store')->name('store');//list function add edit remove
            //edit
            Route::get('/show/{id}', 'PizzaController@show')->name('show');//update page
            Route::post('/update/{id}', 'PizzaController@update')->name('update');//update
            //remove
            Route::get('/delete/{id}', 'PizzaController@delete')->name('delete');//remove
            //ban
            Route::get('/ban/{id}', 'PizzaController@ban')->name('ban');//banned
            //unban
            Route::get('/unban/{id}', 'PizzaController@unban')->name('unban');//unbanned
            Route::prefix('dop')->name('dop.')->group(function () {
                Route::get('/index', 'DopController@index')->name('index');

                Route::get('create', 'DopController@create')->name('create');//list function add edit remove
                Route::post('/store', 'DopController@store')->name('store');//list function add edit remove
                //edit
                Route::get('/show/{id}', 'DopController@show')->name('show');//update page
                Route::post('/update/{id}', 'DopController@update')->name('update');//update
                //remove
                Route::get('/delete/{id}', 'DopController@delete')->name('delete');//remove
                //ban
                Route::get('/ban/{id}', 'DopController@ban')->name('ban');//banned
                //unban
                Route::get('/unban/{id}', 'DopController@unban')->name('unban');//unbanned
            });
        });
        Route::prefix('order')->name('order.')->group(function () {
            Route::get('/index', 'OrderController@index')->name('index');
            Route::get('/edit/{id}', 'OrderController@show')->name('edit');
            Route::post('/update/{id} ', 'OrderController@update')->name('update');
        });
    });

    Route::namespace('Client')->prefix('client')->name('client.')->middleware('Client')->group(function () {
        Route::prefix('order')->name('order.')->group(function () {
        });
    });
});
Route::namespace('Client')->prefix('client')->name('client.')->group(function ()  {
    Route::get('/index', 'CatalogController@index')->name('index');
    Route::get('/check', 'CatalogController@check')->name('check');
    Route::get('/pizza', 'CatalogController@pizza')->name('pizza');
    Route::get('/drink', 'CatalogController@drink')->name('drink');
    Route::get('/fetch_data', 'CatalogController@fetch_data')->name('fetch_data');
    Route::get('/search', 'CatalogController@search')->name('search');
    Route::get('/map', 'CatalogController@map')->name('map');
    Route::prefix('order')->name('order.')->group(function () {
        Route::post('/guest', 'OrderController@guest')->name('guest');
        Route::get('/payment', 'OrderController@payment')->name('payment');
        Route::post('/post', 'OrderController@post')->name('post');
        Route::get('/index', 'OrderController@index')->name('index');
        Route::post('/user', 'OrderController@user')->name('user');
        Route::get('/store', 'OrderController@store')->name('store');
        Route::post('/create', 'OrderController@create')->name('create');
        Route::get('/delete/{id}', 'OrderController@delete')->name('delete');
    });
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>

    <script src="{{ asset('js/app.js') }}" defer></script>
<!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('header')
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('client.index') }}">Catalog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('client.order.index') }}">Order:{{session()->get('prise')}}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('client.map') }}">Map </a>
                        </li>

                        </li>
                        <form class="form-inline" action="{{route('client.search')}}"  enctype="multipart/form-data">
                            <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    @else
                    @if (\Illuminate\Support\Facades\Auth::user()->role==0)
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('admin.catalog.index') }}">Catalog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('admin.users.index') }}">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('admin.order.index') }}">Orders</a>
                        </li>
                    @elseif (\Illuminate\Support\Facades\Auth::user()->role==1)
                            <li class="nav-item">
                                <a class="nav-link" href="#">Catalog</a>
                            </li>
                            <form class="form-inline" action="{{route('client.search')}}" method="POST" enctype="multipart/form-data">
                                <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
                            </form>
                    @elseif (\Illuminate\Support\Facades\Auth::user()->role==2)
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('client.index') }}">Catalog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('client.order.index') }}">Order:{{session()->get('prise')}}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('client.map') }}">Map </a>
                            </li>
                            </li>
                            <form class="form-inline" action="{{route('client.search')}}"  enctype="multipart/form-data">
                                <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
                            </form>
                        @endif
                    @endguest
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>

    </nav>
    <main class="py-4">
        @yield('content')
    </main>

@yield('javascript')
</body>
</html>